var courses = {
    "MATH 11":  {   name: "MATH 11",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "MATH 12":  {   name: "MATH 12",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "MATH 13":  {   name: "MATH 13",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "MATH 14":  {   name: "MATH 14",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "AMTH 108": {   name: "AMTH 108",
                    description: "OR MATH 122 if you're a WDE major",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "CHEM 11":  {   name: "CHEM 11",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: false},
    "PHYS 31":  {   name: "PHYS 31",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: false},
    "PHYS 32":  {   name: "PHYS 32",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: false},
    "PHYS 33":  {   name: "PHYS 33",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: false},
    "Natural Science":  {   name: "Natural Science",
                    description: "",
                    hasLab: true,
                    COEN: false,
                    WDE: true,
                    quarter: "Fall"},
    "COEN 10":  {   name: "COEN 10",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: true},
    "COEN 11":  {   name: "COEN 11",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: true,
                    quarter: "Winter"},
    "COEN 12":  {   name: "COEN 12",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: true,
                    quarter: "Spring"},
    "CTW 1":    {   name: "CTW 1",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true,
                    quarter: "Fall"},
    "CTW 2":    {   name: "CTW 2",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true,
                    quarter: "Winter"},
    "C&I 1":    {   name: "C&I 1",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "C&I 2":    {   name: "C&I 2",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "COEN 19":  {   name: "COEN 19",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: false,
                    quarter: "Spring"},
    "Core":     {   name: "Core",
                    description: "",
                    hasLab: false,
                    COEN: true,
                    WDE: true},
    "ENGR 1":   {   name: "ENGR 1",
                    description: "",
                    hasLab: true,
                    COEN: true,
                    WDE: true},
    
};
